/**
 * Converts the brand's raw photography into web-ready WebP plus tiny blur
 * placeholders. Run with `npm run assets` whenever assets.manifest.mjs changes.
 */
import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';
import { SOURCE_ROOT, IMAGES } from './assets.manifest.mjs';

const OUT_DIR = path.join(process.cwd(), 'public', 'images');
const META_FILE = path.join(process.cwd(), 'src', 'data', 'image-meta.ts');

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.mkdirSync(path.dirname(META_FILE), { recursive: true });

const meta = {};
const missing = [];

/**
 * Studio shots sit on a sweep that photographs slightly grey. The hero and the
 * marquee blend these with `mix-blend-mode: multiply`, which only disappears
 * cleanly if the backdrop is actually 255 — so lift the whitepoint just enough
 * to get there, sampled from the corners rather than guessed.
 */
async function whitepointGain(abs) {
  const size = 24;
  const { data, info } = await sharp(abs, { failOn: 'none' })
    .rotate()
    .resize(size, size, { fit: 'fill' })
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const corners = [];
  const at = (x, y) => {
    const o = (y * info.width + x) * info.channels;
    return Math.max(data[o], data[o + 1], data[o + 2]);
  };
  for (const [x, y] of [
    [0, 0], [size - 1, 0], [0, size - 1], [size - 1, size - 1],
    [1, 1], [size - 2, 1], [1, size - 2], [size - 2, size - 2],
  ]) corners.push(at(x, y));

  corners.sort((a, b) => a - b);
  const median = corners[Math.floor(corners.length / 2)];
  if (!median) return 1;
  // Never push more than 15% — beyond that the backdrop is not white and the
  // image should not have been flagged in the first place.
  return Math.min(1.15, Math.max(1, 255 / median));
}

for (const { out, src, max, quality = 80, whiteBackdrop = false } of IMAGES) {
  const abs = path.join(SOURCE_ROOT, src);
  if (!fs.existsSync(abs)) { missing.push(`${out} <- ${src}`); continue; }

  const pipeline = sharp(abs, { failOn: 'none' }).rotate();
  const { width = max, height = max } = await pipeline.metadata();
  const scale = Math.min(1, max / Math.max(width, height));
  const w = Math.round(width * scale);
  const h = Math.round(height * scale);

  const gain = whiteBackdrop ? await whitepointGain(abs) : 1;
  if (gain > 1.001) process.stdout.write(`  (whitepoint x${gain.toFixed(3)}) `);

  let base = sharp(abs, { failOn: 'none' })
    .rotate()
    .resize(w, h, { fit: 'inside', withoutEnlargement: true });
  if (gain > 1.001) base = base.linear(gain, 0);

  await base.webp({ quality, effort: 6 }).toFile(path.join(OUT_DIR, `${out}.webp`));

  // 16px blur placeholder, inlined as a data URI for instant paint.
  const blur = await sharp(abs, { failOn: 'none' })
    .rotate()
    .resize(16, 16, { fit: 'inside' })
    .webp({ quality: 30 })
    .toBuffer();

  meta[out] = {
    src: `/images/${out}.webp`,
    width: w,
    height: h,
    blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
  };
  process.stdout.write(`  ${out}.webp  ${w}x${h}\n`);
}

if (missing.length) {
  console.warn('\nMISSING SOURCES:\n' + missing.map((m) => '  ! ' + m).join('\n'));
}

const body = `// GENERATED by scripts/build-assets.mjs — do not edit by hand.
export type ImageMeta = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const IMAGE_META = ${JSON.stringify(meta, null, 2)} as const satisfies Record<string, ImageMeta>;

export type ImageKey = keyof typeof IMAGE_META;

export function img(key: ImageKey): ImageMeta {
  return IMAGE_META[key];
}
`;
fs.writeFileSync(META_FILE, body, 'utf8');
console.log(`\nWrote ${Object.keys(meta).length} images + ${path.relative(process.cwd(), META_FILE)}`);
