// GENERATED by scripts/build-assets.mjs — do not edit by hand.
export type ImageMeta = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const IMAGE_META = {
  "hero-ratlami-sev": {
    "src": "/images/hero-ratlami-sev.webp",
    "width": 1448,
    "height": 1086,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwABABoJagCdACpqkf0OBAAAPxcZWX3YZWKUCwqkCD5Lwre4sv1n2qgcuJ4aBio7LA7dFrOFBNlyC249FtuWxj+SE6PHm8BN04AAAA="
  },
  "brand-best-bites": {
    "src": "/images/brand-best-bites.webp",
    "width": 1448,
    "height": 1086,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwABABoJagCdAC3WdugrAAA/tfkR01i5stAn0yx3BYT6OjTbwipr04Hl35C7ktUfquTmrrlGisKJFvWel7dV5JY9MXiAAA="
  },
  "brand-bapu-best": {
    "src": "/images/brand-bapu-best.webp",
    "width": 1672,
    "height": 941,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkABABoJbACdADvv0WwAPwvj1pPIDi5K2DWblRLPZ1n5gTpA7IDhLAKp2VPgn2Akrxgkw6exHcweoIsV2ZsL5ni4EAA"
  },
  "p-ratlami-sev": {
    "src": "/images/p-ratlami-sev.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMABAABABoJbACdAYv1bM7WOWaEQAA+Wi9shFMF/CJ9B5SCcX2lZFFfMLy9/bKp7ptFl312+rRxl93Ubp80P4B/gHn0zvjKi8tPcAKSbq+rgAGLnUOrIpsjPgAAA=="
  },
  "p-sada-sev": {
    "src": "/images/p-sada-sev.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoMABAABABoJbACdAEUPUCQAp9NAAD+t9cKhiyVXMvNFwkHUONzwLIuNw+U+qhPEQ0j/3IZdUGUBZrzOWsC1h+ro835CV1RhJAFQrHOP6qM6ysgAAA="
  },
  "p-milan-mixture": {
    "src": "/images/p-milan-mixture.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoMABAABABoJbACdADc6tKsEAD+55Q67rZUruHiGV+0LrMVXUJf6KQRxC4Wiqb+DoymNMCbtcc3yge2iFxBk/gwfM4kQzBQYqUkL1RNh5GbFqQRNZV6a5gAAAA="
  },
  "p-kadipatta-mix": {
    "src": "/images/p-kadipatta-mix.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMABAABABoJbACdAEYGvYTigAA/tgoElTIWLLqh+UtAyWIj3wcgS2cK4JCUedU+JdazjykcrqJ7WbKOGtT6QzoDp69Zy0vAAA="
  },
  "p-indori-khatta-meetha": {
    "src": "/images/p-indori-khatta-meetha.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoMABAABABoJbACdADQit45kgAA/rfos1BkMK8nBXuLgD90t2pHG9aGPFnRArKy48rqKArV5POcbol9f4cOIIFvhtcb4m7cjEHgzKz4c4tWwAAA"
  },
  "p-lahsun-mix": {
    "src": "/images/p-lahsun-mix.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoMABAABABoJaACdAEKrs69TxIAAP5ssGZAFFHu5ZhBpP99DoS0pWtfXWyPK3Yr/cwCYIANryu9XFvBQ5HEPhSy3xd0pfifbeyMMHxculT4CE32NoAAAA=="
  },
  "p-waffer-mix": {
    "src": "/images/p-waffer-mix.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoMABAABABoJbACdAYt9bWxKYXetgAA/sdeGeToliXV7tKUjg2OOG/xtVkL+DQ0jNt9SRsaLis+vs1mOwLaSf31DR9wyIM87BDrtLgy6cbLrXIGhAAAAA=="
  },
  "p-ujjaini-sev": {
    "src": "/images/p-ujjaini-sev.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMABAABABoJbACdADbYwb0/V+AAAD+6pVSF0tmv/Y2Dhoxl00g88HIeLni49xx6b1cSIfgT0v4er+RopjfRuLWpC0/Ouu+8AAyQWwXrDll2RROYCCtoAAA"
  },
  "p-khatta-meetha": {
    "src": "/images/p-khatta-meetha.webp",
    "width": 675,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoJABAABABoJbACdADdtpJAfioAAP3dwPyCcAldxgdY4iRaHRGIC4eaB5T8soJPoSWHBAPeUDADNmXJdAA="
  },
  "p-hing-mixture": {
    "src": "/images/p-hing-mixture.webp",
    "width": 675,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoJABAABABoJZACdADcUCoUMFgA/fxd+WPrf9juvQulPlRVjqH52kuf8O600wEp2GifbBZwjkNFYwO796BC9DIAAAA="
  },
  "pack-ratlami-sev": {
    "src": "/images/pack-ratlami-sev.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoMABAABABoJQBYheADCNehC/3HQAD+67EFtVeQKtQrzR84hmg3pRycf6YS29x6lsGpbq3seILYcX224p2d4RptOm5dOfU6OfqlqgA+whGXvNlVVRzXhKdAAAA="
  },
  "pack-sada-sev": {
    "src": "/images/pack-sada-sev.webp",
    "width": 845,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoOABAABABoJbACdAEPhweaSs4AAP7uZOSWU/EAtlonOCqkuOYcgoXWyhx7K7sXPlxMQnjyBuit6SLAjvxypzm9sh8YA33x2eRWmH9ruy0IunoH7B4NIhj/yj4jEGWop9v2JeXZA7AAAA=="
  },
  "pack-milan-mixture": {
    "src": "/images/pack-milan-mixture.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQAgCdASoMABAABABoJbACdAYubwMwChD52igA4nwauv9KIjBkcZFCeJBn4BGMNIIfoZ050jBfKSiX+XYGdlMmx/AlIHXfd8KXPMhB5o5xerggfcxvmcFH2mIOXFjo2N8X+l77m4LAtjzxlSnJLwAA"
  },
  "pack-kadipatta-mix": {
    "src": "/images/pack-kadipatta-mix.webp",
    "width": 1000,
    "height": 908,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAQCdASoQAA8ABABoJbACdADprpYcuAAA/uiq4g02DledRJAHOA+ycV7g9bnHSfTMsW7TYrGmv73j2WxeL4L5yw/7XKX6YqcVoySlkki5WXF0ZCwgeKmgvvgsgz39BPF2OW4ragzRbb3lyojIPWA12MAAAA=="
  },
  "pack-indori-khatta-meetha": {
    "src": "/images/pack-indori-khatta-meetha.webp",
    "width": 1000,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwAgCdASoQABAABABoJbACdDiAN45BkTS94Df6iGAA/u5k5PJCcZPCHGW8ekXh3ARlzEhLFCOlV5YOQzXlwXAU3UvQ/XShbGDi11kItYjME4R7RjKaz/RjROTKoCJZ/CRyg2FqwJcNJZMeEyWQs1bOjiPYz1NJstfwokwAAAA="
  },
  "pack-khatta-meetha": {
    "src": "/images/pack-khatta-meetha.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAQCdASoMABAABABoJbACdAEPAu6S1aAA/tghqp8AVi3r6wdKm+IJwBbxXc0sylrerUHVU9XwQBLDmHSujl3vf20dyQr1zhhqPdvd4FmOM69sAeMIs06mDdXx/dOFeUtEK5tBMt3o4hZU1+Y7WPdBQ6IsAA=="
  },
  "cut-ratlami-sev": {
    "src": "/images/cut-ratlami-sev.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRkQBAABXRUJQVlA4WAoAAAAQAAAACwAADwAAQUxQSJwAAAANgFzb1vLkvBdPRgkzd3pgxqIlOgh9aANU4DZ3d3d3+N/FioiICTDxvyOlCp5ExFdiRtdwJPH5+arqKM8tnsnkcoXs4Q5r6fbEUPprE3u5bDRDfniKx3WNDNkG5nFSC8jmScFRPWDMgTiuc5S+3CT+kX/0kfoSZ+Wc7Ll78dngoZRClZ7JK4vOXmHxXsUTnvpHcvq4ARkn67wBLglWUDggggAAADACAJ0BKgwAEAAEAGglsAJ0Bi/WPvPtTDUgAP6o4C8y61PYkexJyPLNOs069mxL3OEb3g8Milv6KF6t9POH4wdOR3sn4lmzB7oswLXLiLWbrIfihOBDmyqqZ59B3liGxUwhxB8gQnrdSAT/gsZbZd/xrlVWw+Pf4M7ZBAOy2ECAAAA="
  },
  "cut-sada-sev": {
    "src": "/images/cut-sada-sev.webp",
    "width": 845,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRlYBAABXRUJQVlA4WAoAAAAQAAAADQAADwAAQUxQSKIAAAAJgFvbtmplnfu+u/v/aKb9UA2d0AAhKam7u3vmzr3Pe4iICRB7JPX+p37037f5/bWtmeWN3Z3D4/Ozu2lb6Xci8VgimSpkswiL2MFcI8yiED8bgEYAbIst4DuEu2ts7l8JOn9Shss7bPxrKMS8EbwMYreHEbCtj01soZoGMMwfKCO04kYA/hCghcHWmj5liDMCiIr9bVs28cTZmeZ5bmpiUgtWUDggjgAAADACAJ0BKg4AEAAEAGglsAJ0Bi1U1CdVy/AAAOJ3zgWMZHB1CA/yjXp2iHzD0jIBGAsD4vZMm6MAQqAf9+uNalrk3bNMkAAUDxO7xb4fEFWYaD/c3/y7LqsVa5qFjY9TeHu/Ap03iYVeHPxn/kYXjnLe/mGYu0gppFKN44i/y5Y82c3gj/onGd8J5EwAAAA="
  },
  "cut-milan-mixture": {
    "src": "/images/cut-milan-mixture.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRiwBAABXRUJQVlA4WAoAAAAQAAAACwAADwAAQUxQSJEAAAABgGNrm/Jk4i611WldNpBUXia4Q+tQu3vpsALW4U7l7pSRj5m3mZ81RMQEJFYXFuenpsanJlbi3SBIq2gtoEJEVKUSakIcAgAER0p/BC5Bxc928Sf7cbFhGceTgXVByK6YakVpj7Ft8H9sKZ0ztqN0rdIdKz1onZ+oEhFV8Or0VSEAQODXa8+3D03Mzo33NyZNAFZQOCB0AAAAUAIAnQEqDAAQAAQAaCWwAnQGLQXM2jRCmU0AAP6DsP0NeIF3f2NMRd4q/zszZU1KEPlQX/KfiyJWqhaBRZNQ0ATLgcpHqiojD4R4ELmmw9V7nYjtooLWmeLJUyTxJ00GtGnifevCTbrcGHCuiir4BScAAAA="
  },
  "cut-kadipatta-mix": {
    "src": "/images/cut-kadipatta-mix.webp",
    "width": 1000,
    "height": 908,
    "blurDataURL": "data:image/webp;base64,UklGRkYBAABXRUJQVlA4WAoAAAAQAAAADwAADgAAQUxQSJcAAAAJgFvbtmplnfd+6O4uuEMBENMQjVAEBTBIPXK30CN3u88OPUTEBFhmfvYu9/v59/n6m1ucs6BcGa82+4empmeGuyA8Yxyde8TiDNFhH3HYxCbo2JyA4fhTnAByf4aBuwsUh5tLcZzQ1wpG28ECWMIOwDICQhOjvWg5nIBDGMAQ59+fgEMYCThEtSSqEFZk4852cHhaWMEAAFZQOCCIAAAAkAIAnQEqEAAPAAQAaCWwAnR/AIKsxVCvGwatytgA9rNu5ZKpkndlmWz1DPebtMUI7dhnpm6QIVp1cvqptYbYGzxqj4X4go1ZEXE62TkiDmLy5tIO6H9hidIp5KRzpANXieE9PcRm7QHPplP84Hosa/XyiQkbGNcP2Lq2vAuwdhs/02q/y+AAAA=="
  },
  "cut-indori-khatta-meetha": {
    "src": "/images/cut-indori-khatta-meetha.webp",
    "width": 1000,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRmwBAABXRUJQVlA4WAoAAAAQAAAADwAADwAAQUxQSLQAAAAJgFvbtmplnfs+2gKxZy4pDbhUQw3UQOTukGr2C8Ddne9yd/De+zVExAQ439BGdWCByev0zQUMHuxura8tLy0vr/XgIIMp7KEI4hWwsCv/IvFUdESnP0D87H+aAJF6QVA6vCEE7ykTpEpnJScQ9xgik5q5ogKCYvWjiHwJGZ9jjbgK4HfSecDxiUD8npdN8vAHoc/ZpMnM+VSIqtfkVKGQzX6/DNSXQaW/y6Pu/v6+9sbpPABWUDggkgAAABADAJ0BKhAAEAAEAGglsAJ0ZoDbAXYBvGwIezN4P9uAAAD2l4D3RPovqD4EGtZwyKLWwCnaziJUmvL0v40i0YWv+9V2Kcf65/rRggeyUw3A2LWQ1j/UW97feUOMcGnGvTVu8GUftWtLZqRxW3jsVlnikCcj+avtXVsQfAgENH3+9BBF8f6D4M+fTN0CZm7ziCAA"
  },
  "cut-khatta-meetha": {
    "src": "/images/cut-khatta-meetha.webp",
    "width": 750,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRi4BAABXRUJQVlA4WAoAAAAQAAAACwAADwAAQUxQSJUAAAANgFvbtqpqnYu7u0MEIaR0QgNkVKNfGnKJ3d1dn/cQERMgGs7SGV163F73v/bjGt8N2xqg8L4tX+72v5SA5jn4Y6/lFkBjG04qgkVW4KimNEHzaDtwXhQN4P4WbmJerF7XBw8Bv43b80H8C1tRf5Sw93jeyfPj0kDzRR7poQTkl+5GYHe5mHnV5Pd/oD4X7q4uQeMfAQBWUDggcgAAAFACAJ0BKgwAEAAEAGglsAJ0ugDK/wPpd57cAAD79A8eObTWzV5OysgQ53c8i7k/uTd/sZSZnFlEeQdHr3x5RdkKUv3olBt1LO64hVErcd02Yvt0kj6FPP5Crk2hNqykB1+5MxP8Zh3JU5bFcLrtiGAAAA=="
  },
  "pack-bapu-ratlami-sev": {
    "src": "/images/pack-bapu-ratlami-sev.webp",
    "width": 878,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAgCdASoOABAABABoJbACdH8BDgbTGDw5M0UV0AAA/tgR/B9uOIyDaIG2828JO0oz905RGMA6L8o1jDWKTiIyPdi4FohYpaRTby/xbfgnSJNAc9E6aKZSFtQuUWmPvQW8jjBhFwq2aYDGQYgAAA=="
  },
  "cut-bapu-ratlami-sev": {
    "src": "/images/cut-bapu-ratlami-sev.webp",
    "width": 878,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRkQBAABXRUJQVlA4WAoAAAAQAAAADQAADwAAQUxQSKcAAAABgFtr29rmFUudGSZw6+MB2Gl5AOaKOWmZmVrmMbJAqrTpmSN4A792iIgJMMaWhxorUsl4IJyttJRruuTX29vTPW8NjPHT8UjS5jSQ/qT33/WYh4wrOiTp8i4IBce0/zm8gKxiX2RzGKqKPb9uqBrm/Qah6pj264KmYUv0zbZ/6yKbHdA1jIocrsiGgm1+2v+/eSSjjy6FLm8UZOsHZicnhno6muoyKgBWUDggdgAAAFACAJ0BKg4AEAAEAGglsAJ0Bi/WBfVCX2zEAADidk2LXgDf3va3Y0G2VHqqGFl04JdUJhpHHJFjnnYZJ2hhGSK67qlCRg+mdSUp9a7tqfSPeDjBKunFyBQiWfIiTlJYCT/MZ/l/dgEHotKYN5XOwvUuT98guAA="
  },
  "card-bapu-ratlami-sev": {
    "src": "/images/card-bapu-ratlami-sev.webp",
    "width": 1000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoNABAABABoJbACdAEPAlBizJwA/u3hhKRmR+S614Z3ze3Pg9uBth32AUBOG4QpYYKJ9Ten0VJJAQfCM+5OL3/3pTSCCBs8IwBLwAAA"
  },
  "pack-bapu-lahsun-sev": {
    "src": "/images/pack-bapu-lahsun-sev.webp",
    "width": 928,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQAgCdASoPABAABABoJbACdH8AGAGtWJOgycgkAAD+6KDFixUXMs+xMjQAIV3woXpBJUW7s22nTpNjWhJiOBzoGcDN1qnxI5dBdjwCKvBy7c5Q4A7rxZzbwQ589uXPYdg7azB4wLPcgBUhYL4bi2aVbOF2kbXRi20tDGQA"
  },
  "cut-bapu-lahsun-sev": {
    "src": "/images/cut-bapu-lahsun-sev.webp",
    "width": 928,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRmoBAABXRUJQVlA4WAoAAAAQAAAADgAADwAAQUxQSLsAAAABuS5E9D8Auba1Y895nve3Nf7nfxGMVYH6yjQVGBWoADVg23nfJ3jTQ8QETIBOyMhJQVZFSUlKSt6CZ8G8Oa8S4CQJGHGiBVj0ocgIAIGXtOuBEqu2DPMcAEphFxzlnQIEACgcglE4gqgRXw7AAG9iwKNHf579l+IABhegYhlJEAJ5MDGVBgAFMQHR8CcNcSPqIIBPfwyEQQHwBX0wAQS8IGkMAtPUhgQBwDGYNm4Tbk0pcrzAU2kmMHsAAFZQOCCIAAAA8AEAnQEqDwAQAAQAaCWwAnQGMTxmjxaAAM3mKSbYvRYqzJANRD/RXgitHiI2F1js1RCkgs1jszyMImQus9jhzG43Wpsu9JgnE29lxPyh0k9WVOnotsaq9t1RqoFTBpPvCqqomt7AYgEc2fAZPLO03hy0pIppOIHpPp7Z2qMuC56+/w9e4+AAAA=="
  },
  "card-bapu-lahsun-sev": {
    "src": "/images/card-bapu-lahsun-sev.webp",
    "width": 1000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoNABAABABoJbACdAEPBdLF9gWAAP7t4YTa7Bfas0IBKsF6Cay/ihKzK3yJg0wIsgFgU3k4UW19zan9m85EJy0qWkvU586E9XX6q2KHFiaO1+AJfQAAAA=="
  },
  "pack-bapu-wafer-mixture": {
    "src": "/images/pack-bapu-wafer-mixture.webp",
    "width": 875,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQAgCdASoOABAABABoJbACdAEPhb6bsswAAP7t6wDjlUsewwtCELjG6XtE81TNFPypC7/g4+sD8k2R6lo3vrk2klyYSPE+4viXBFtGkkrGGITScEZ6dxUH5Ii8WaxiH3C5aVFTyo6eYMiWMrWm6C7DBTn5qN0DJigAAA=="
  },
  "cut-bapu-wafer-mixture": {
    "src": "/images/cut-bapu-wafer-mixture.webp",
    "width": 875,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRmQBAABXRUJQVlA4WAoAAAAQAAAADQAADwAAQUxQSKkAAAANgGLb2rLlPM///7hD0uZujUyFymJWTrfEBNw9enVL7rzyYIOIiAlIpRHS0tIyQmVp0clMz9g92eKcWuB4eLO+TQDETMa53e31Cf6m3k5gryXJX+PmFeY7SkyAqCskuH6oj8rfc0T9Sx7/Jz0ar8pM/rlAxO6K/hEeMHjLEsAUA6OIvxK0e968doIBQtdmoDSDBIBS1TpN34vzzkeIaf1zMjCV8s6CmLwiAFZQOCCUAAAAsAIAnQEqDgAQAAQAaCWwAnRH/9klkRaVTbwo7mqQAP7KTjrFxX0qC/idoSyU4fneDaSZh0P9nSqtqkz/smaH0gE9bZG4A96XpLj4dtEorDPDIrirN5xYg1dATetcvo3niv+M3D4a1MDzvnbyA+TkdjSQ4XGf+OfrVzzX2p8H+UP1AspE9C0rQcy0J9xD2NwC3gsAAA=="
  },
  "card-bapu-wafer-mixture": {
    "src": "/images/card-bapu-wafer-mixture.webp",
    "width": 1000,
    "height": 1250,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoNABAABABoJbACdAEPDaXxrOXKAAD+79FTR2IuUCstn4hEJMrI+8sB6Yn7Tsl8X+uakGEj6JhWrFchmLGkAaGjz2urcatdYERyQGsqwIZC1mRegAA="
  },
  "detail-bowl-khatta-meetha": {
    "src": "/images/detail-bowl-khatta-meetha.webp",
    "width": 900,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoJABAABABoJbACdADyUMuwAP4FrMudi0yvVR/p+gJp85sLMSuLOdSCL13pzu19DqSmun7Et9bXuSM4HYAmmcgAAAA="
  },
  "detail-sev-scatter": {
    "src": "/images/detail-sev-scatter.webp",
    "width": 1086,
    "height": 1448,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoMABAABABoJbACdADbvy6D9AAAyjxGuJZ6Ch1ZUf0MC033Ww9WFdlGTDsWvpIvXcJx9+4CR1MXD8//Lcvfk5kH29JWrbfPYZvbDN81vLWcoAAA"
  },
  "detail-waffer-pour": {
    "src": "/images/detail-waffer-pour.webp",
    "width": 1086,
    "height": 1448,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoMABAABABoJbACdAYuv28LCjMuUAAA4gR3Gz2ktfF0I+vCEtyXH8hHnszxAV3GIuFQpe9kSvkdJpsathepZ/VmqFkOPDL28baFz8YThW8ecjyr4ijtPU5Aa3E8ZAAA"
  },
  "detail-milan-bowl": {
    "src": "/images/detail-milan-bowl.webp",
    "width": 1086,
    "height": 1448,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoMABAABABoJbACdADMEylot8AA/teUx5xbp3PKnQTiq96CVk0d3L7Dp2fuE906LFvliV8UHxfhMLz02JvJTDR/jiG5o97CknsubwynzRSsfwv+t2xAAA=="
  },
  "detail-ratlami-flat": {
    "src": "/images/detail-ratlami-flat.webp",
    "width": 1448,
    "height": 1086,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwABABoJaACdAEefAgxh0wAAP62uq2UGYzkZ9VGYHRhoYEVEJJatveapBn/NXT4MQaktkuNH10Oow4IJi7W2XT+Fm1uhH4w7X98u35IrgUiMrsH4AAA"
  },
  "detail-kadipatta-flat": {
    "src": "/images/detail-kadipatta-flat.webp",
    "width": 1086,
    "height": 1448,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAABABoJagCdAEfMFoqwrAAAP7U4H2/3EJkKrb5xxwh23v7W9psAQ3OL+UaMwGScXPWvQEqc5K2uTJbVHkWZAGo+U3/o24hKtymQAA="
  },
  "store-01": {
    "src": "/images/store-01.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAcABABoJaACdH8AF8V8pzaAAN5R8/whiSJpZf/lLLjBK+htx7J0UK9xaNIPRcTxkvrY513yPq+IFUEjNBbazFFoAA=="
  },
  "store-02": {
    "src": "/images/store-02.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAcABABoJbAC7AEf8XvagpqRAADLHvO/f2ie0qytJFDUUY+WCurNtZuGSXseTektFzK9sjpnZ3nDiD1i0vXLnWBJmEkdBNgAAA=="
  },
  "store-03": {
    "src": "/images/store-03.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoQAAcABABoJYwC7IExGL/FUTK8AAD+zPX98xT0Y/5k6k9GKMGjUhDWhk2sgpqx1GieI/etZaf/yaFqLJoAWAAA"
  },
  "store-04": {
    "src": "/images/store-04.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAcABABoJQBOgCIHBDZxtAAA/sd7hsYHxrid/CzCAvNpDbJ9WAq1oibdybkpt8pU26Ejvg1DjqVzdAVf949i9wAAAA=="
  },
  "store-counter": {
    "src": "/images/store-counter.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAcABABoJbACdADLuWpM5rYA/q1eUMREVEKKmiXsDTaDoQhkEzS/svoUrUM+g5b70omfzVOpJ4rPKdCArYAA"
  },
  "store-sweets": {
    "src": "/images/store-sweets.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAcABABoJYwAAq/wGdpfgAD2tjC/GMjHxK3YZaOcHNdbjmlHdISJNNZ+5VH+Wt3yneklZN7k75r9OgzsAAAA"
  },
  "store-mithai": {
    "src": "/images/store-mithai.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAcABABoJYwCw7D6jKO50AD+Q0KbFm67h8c/EOgPLAagzBio6uIMMRSsKWQAAAA="
  },
  "store-shelf": {
    "src": "/images/store-shelf.webp",
    "width": 1600,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAcABABoJYgCdAENfK6ayiAA/nhmJ7YuecaUTQxCuF09Utm8mcLBdDpyQWhKE9M8Dk8WPpewcOjKgAA="
  },
  "g-ratlami-b": {
    "src": "/images/g-ratlami-b.webp",
    "width": 1200,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAwABABoJagCdAC9Hk+CgAD+WpyP5l+fSpx6Mg6o6BT5wpW5wJTUFtkhjuzIeF6QkDBG8zbGYDSObu+Bz07yEvWwEUMxe8yG75Z3sGoJ1KbcrgAAAA=="
  },
  "g-sada-b": {
    "src": "/images/g-sada-b.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoMABAABABoJbACdADCoXUAAP7KmllLU17+9+zr9fxcHS6d4EsONTukls43MOnrzehjn2eLeLbAHiZ+MYV56GyXwIMUXg0CiGqa8NMgAAA="
  },
  "g-milan-b": {
    "src": "/images/g-milan-b.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoMABAABABoJZgCdAYtpbMnkNHaAAD9KM0x+GWNgGevTBVgfl5p7Hp3tFx06Z7+Li6m59MNtE2rZoYTDlds8sCQlF7zWwnMHJlStVB6HMZ6zPXO/K6TEXDI87vjX5Y8AAA="
  },
  "g-kadipatta-b": {
    "src": "/images/g-kadipatta-b.webp",
    "width": 1200,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAwABABoJagCdAD5PGldAcUAAP7Uo3c9WcEBMNNSQmUgNgdT/ees8G0W2vobWuoHmwizHQNoxl++fzx73UWRnZD2AAAA"
  },
  "g-indori-b": {
    "src": "/images/g-indori-b.webp",
    "width": 1200,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAgCdASoQAAwABABoJagCdAEYFxsX8mhJYAD+8GYzdDDmfm89M0yOdXOS6Sg1BIGMMk9kct2qwNayHyLrNfOXOmv7aALbTHYAAA=="
  },
  "g-indori-c": {
    "src": "/images/g-indori-c.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoMABAABABoJbACdAEPDV3C9PwA87ObsmdbfrkP9E58F7twHTHHqx7APS/B39g0mRjA6r/UXOmvNKM5f4SN/p2KeqyeLgF77z4y5iuFO9SAGof5PFzCQAAA"
  },
  "g-waffer-b": {
    "src": "/images/g-waffer-b.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoMABAABABoJbACdAEfQ/vWHleVMAD+mxuAMuu2kZjpE1JfwWqjKeS2o1tV/IoLWjBDjOzm+LditRW6IlOqiVl55P3mkxX1b1VTq9P8t894f1Xhy7XCoEtYAAA="
  },
  "g-waffer-c": {
    "src": "/images/g-waffer-c.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoMABAABABoJbACdAEfUWnASyoAAAD+4aFeYSvpvmH72gtyMfvGfN6pRZ20VZCW0om0FsMoI+LZKteiKUQ5mZ+CwhOW/c7oh/lNkUUJozMxuA7s23CebWk+j/qcAAAA"
  },
  "g-ujjaini-b": {
    "src": "/images/g-ujjaini-b.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMABAABABoJagCdAD1esobPyAAAP3SFJuoYuEfdHIBjgFXufKt3Kv/2CZJbpGuwFMFEsAYwCgjmsDBsmAUTnvcz4SaJ+3SZoxvSAAA"
  },
  "g-ujjaini-c": {
    "src": "/images/g-ujjaini-c.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoMABAABABoJbACdAELhqz+3XaQwAD5UUl+f9fM63Z8t7pv0J+q+aBQaNrw+h5sLvHbNw8OTQa3gqz+HBPNYCYsHnACtw/o1qDot3HIAAA="
  },
  "g-ujjaini-d": {
    "src": "/images/g-ujjaini-d.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMABAABABoJbACdAYvX28zaiMf9AD45UzG1c3ZUJxPmVdTyQSgDxFCwmZX9ZzkYMSpadU1v45EMUM708e159n44BOqAlS+l4AsGlEH0l04X9Ng5Inc6gAA"
  },
  "g-lahsun-b": {
    "src": "/images/g-lahsun-b.webp",
    "width": 1200,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwABABoJagCdAED9Xy/vBeAAMyXrXCN/dcfNgyssPbSjYUbd/uVDS+RD/xm3qGeCnJwx0waHxgVz/aSNVTOu8f3YjDckTcH7xuYQAA="
  },
  "g-lahsun-c": {
    "src": "/images/g-lahsun-c.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoMABAABABoJbACdADhkKrQLiAAAPp0de+vZF94lZN/ekO/4wOh/xmjJjT6U2xNweioJzRA1m312RegfFApEve9DTFQDVJ+82CJbrDxcMfh488kQvs265MiAAA="
  },
  "g-lahsun-d": {
    "src": "/images/g-lahsun-d.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoMABAABABoJbACdACnvsujuEAA/kSKnUSY931EXz5evyG23ZDf9egiP8gAmrh4W2R13j/y9sSMwbvtU/0Syc9ps9lXeU4yKDe35XRXVIk782DHnw+/1cHMmwWCTU+PAAA="
  },
  "g-khatta-b": {
    "src": "/images/g-khatta-b.webp",
    "width": 675,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoJABAABABoJaACdADdoeLhaAD4Mi+TvbsgQRtePLFreVUQLKtS1KrP8YTMICnaL0MN/lAALgVxseAS2OgDzbTE7niUyEKJ+AAAAA=="
  },
  "g-hing-b": {
    "src": "/images/g-hing-b.webp",
    "width": 675,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoJABAABABoJQBOgCICc9PMIwAA/tRkNTNSM46ptqFljN3e/7zCogYUv9ZMvTOwZPBfY095rwwgoGRgAAA="
  },
  "g-hing-c": {
    "src": "/images/g-hing-c.webp",
    "width": 675,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoJABAABABoJQBOgBrSfW1AAP7UNx0Qzf7nxzZNHyGFmECtJwv1WJHkXTFxl7DmKm2N3D2MAAA="
  },
  "label-back": {
    "src": "/images/label-back.webp",
    "width": 1050,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoMABAABABoJbACdAEDFWEqpwAA+Wk0kTuPcpsU4Sg/NM2PfodX6J7/kanwAJjOW/df44hIivlOzMgQDlg2nYPI3XHLwVoP2H4I/a35b5DYupYlu+XVRRt4AAA="
  },
  "story-house": {
    "src": "/images/story-house.webp",
    "width": 1394,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoMABAABABoJbACdAEf1u5IJr3KB7AA/tKMIei1ajjYadou0ApRkfabUH+HjOABY7xTyGlVHhilkTMpX2V+FJ4xZURWrJ0Q2GbirdLN26xsG4EJrjOY6lXrgTWwCkAIwAA="
  },
  "story-spice": {
    "src": "/images/story-spice.webp",
    "width": 1800,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsABABoJbACdEf/gWX7a8b6DAAA/vSQjwzi2G+XvMPR7haR/MEdHA78ZccJ8epF2iVkHRRArvSlbHFzv8DSfiMwYowVog7xY4AiEc0wAAAA"
  },
  "story-table": {
    "src": "/images/story-table.webp",
    "width": 1583,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoQABAABABoJbACdAYw7wK3j22USSKAAP7eA9J7ItNg7iroczw3KXc3Y59HuMBwm3HAOKcYCNpc1bCXpHYQySu5Fadr5JjZjEpnOv6jw3xV2dGPDci8LJRerprm3Yo3ZNJNhG199gAAAA=="
  },
  "process-ingredients": {
    "src": "/images/process-ingredients.webp",
    "width": 1400,
    "height": 934,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAsABABoJZQCdAYtKiuUAAD+jTm0p8lnQ/cmxD3DzL7+oM5FodLt3H1B2cHC+C2FtO90pmvbkkaK5UsXt2JTLnmJdMyAAAA="
  },
  "process-preparation": {
    "src": "/images/process-preparation.webp",
    "width": 1400,
    "height": 934,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAsABABoJYgCdADdLvPYzLAA/uX3M1h9iPM/B9jMRsTxOw/pTdvdtftAe6zr4t19iwUdKC8AnXaBFkkSSTn7k0AAAA=="
  },
  "process-seasoning": {
    "src": "/images/process-seasoning.webp",
    "width": 933,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoLABAABABoJZwAAlLKQep4AAD+FjAAWD09srwfn/oRBbmMP0OAAA=="
  },
  "process-quality": {
    "src": "/images/process-quality.webp",
    "width": 1400,
    "height": 934,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsABABoJagCdAEPSDiuWVSAAPWRx1czX2rFO1aWHzKLhTqI6quGaTHS12iGOE7UNQXDGHdzIF7Oiy/mKPmx5uymiECuLxbzrrsQAAA="
  },
  "process-packing": {
    "src": "/images/process-packing.webp",
    "width": 933,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoLABAABABoJZgAAf/2G7UhsAD+mJVha3EzXudCJGdlNrDTWSgdLvRo1QomwmLa7jvsVRb1hZ4tNqyZwbFFfPWfvEg8lzpvDPL32WPRSHtn5Q/TwAA="
  },
  "pour-bowl": {
    "src": "/images/pour-bowl.webp",
    "width": 1086,
    "height": 1448,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoMABAABABoJbACdADcQcaHegAA/vOHHlQixGdURoPY71A1AFib27WBBnCmvQ/hscwmb83j0cuaNDiWnvMPeGM115JH4OUbtJ4vX1BXpwYiLZDyPKgmL2tuxob+/l2oAAA="
  },
  "shop-front": {
    "src": "/images/shop-front.webp",
    "width": 680,
    "height": 383,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkABABoJQBOgBIuUFQA+NScLPa1UVIlgWT8LeQ96z26NJ0hRdzETUTUOLMzd+3SWf8c0R4zTs0mSd0xlUwtAAA="
  },
  "shop-aisle": {
    "src": "/images/shop-aisle.webp",
    "width": 382,
    "height": 510,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoMABAABABoJQBOgMX/3Evw2+SoAAD9dVGzBWbskeZfOQjM0nD/2u2TUv8GDFckL3j5fvKQ9zIaRmrcYL4jJk1ENSkIFO9ulUuq0Fr5x+QAAA=="
  },
  "shop-snacks-counter": {
    "src": "/images/shop-snacks-counter.webp",
    "width": 680,
    "height": 383,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoQAAkABABoJQBdgBM4BSAA/uwFO9XD7GCjlBMaL2Lc9/De63wOpkEUD4RqXawG84CeAyJYAAA="
  },
  "shop-cases": {
    "src": "/images/shop-cases.webp",
    "width": 382,
    "height": 510,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMABAABABoJQBOgBdAmLrAAAD7zJaHxBRVwhJjk+VuajAqUzt1wTv88ARoJ4aYczIQ4JKx4t/3gkHFsSjODPXrtfdpzZGvFeurAAAA"
  },
  "shop-fridges": {
    "src": "/images/shop-fridges.webp",
    "width": 382,
    "height": 510,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoMABAABABoJQBOgBuS2F7KIADhWz0UXIj+P+5r86lKBQrQVLHjnRzkHgoCFhnbSvEkEKdlrfEqi2K5gQ7+nAs7Ak4we2QwAAA="
  }
} as const satisfies Record<string, ImageMeta>;

export type ImageKey = keyof typeof IMAGE_META;

export function img(key: ImageKey): ImageMeta {
  return IMAGE_META[key];
}
